	/**
	地图画笔功能的基类，所有的画笔都集成此类
	@private
	@class
	*/
	function SFGraphics()
	{
		if(arguments.length<1){return;}
		this.div=document.createElement("div");
	}
	SFGraphics.prototype=new SFGraphics();
	/**
	返回用来装载画笔绘制内容的HTML元素
	*/
	SFGraphics.prototype.getPanel=function(){return this.div;}
	/**
	开始绘制过程
	*/
	SFGraphics.prototype.start=function(){}
	/**
	将绘制点移动到指定的点
	*/
	SFGraphics.prototype.moveTo=function(){}
	/**
	从绘制点划线到指定的点
	*/
	SFGraphics.prototype.lineTo=function(){}
	/**
	结束绘制过程
	*/
	SFGraphics.prototype.finish=function(){}
	/**
	清除绘制的内容
	*/
	SFGraphics.prototype.clear=function(){}
	/**
	设置绘制内容的缩放比例
	*/
	SFGraphics.prototype.setScale=function(){}
	/**
	设置绘制内容的显示位置
	@param {SFPoint} position
	*/
	SFGraphics.prototype.setPosition=function(position)
	{
		SFGlobal.setProperty(this.div.style,{position:'absolute',left:position.x+"px",top:position.y+"px"});
	}
	/**
	设置线条的颜色
	*/
	SFGraphics.prototype.setLineColor=function(){}
	/**
	设置填充区域的颜色
	*/
	SFGraphics.prototype.setFillColor=function(){}
	/**
	设置显示不透明度
	*/
	SFGraphics.prototype.setOpacity=function(){}
	/**
	设置线条显示的线宽
	*/
	SFGraphics.prototype.setLineWeight=function(){}
	/**
	设置线条显示的样式
	*/
	SFGraphics.prototype.setLineStyle=function(){}
	window.SFGraphics=SFGraphics